[package]
name = "keystroke"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
colored = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rdev = "0.5"
dirs = "5.0"
ctrlc = "3.4"

# [[bin]]
# keystr